name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Gemini 설정 파일 생성  # ← 이 단계 추가
        run: echo "window.GEMINI_KEY = '${{ secrets.GEMINI_API_KEY }}';" > gemini-config.js

      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}